Update approval-workflow.yml
NITK-KODE/cms-api pull request #51
Opened 2021-10-02 22:26 UTC by Victoria-DR

Change workflow file being run

2021-10-02 22:30 UTC, Victoria-DR commented
Looks like `pullreminders` was discontinued and the repo owner is now `abinoda` but they didn't update their documentation.

2021-10-03 05:54 UTC, priyansh32 requested changes

2021-10-03 05:54 UTC, priyansh32 commented on .github/workflows/approval-workflow.yml
>          ADD_LABEL: "approved"
Can you change label to `hacktoberfest-approved`

2021-10-03 05:56 UTC, priyansh32 approved these changes

2021-10-03 06:03 UTC, roshgupta approved these changes

2021-10-03 06:05 UTC, priyansh32 commented
@Victoria-DR It's still throwing same error after two approvals

2021-10-05 23:06 UTC, Victoria-DR commented
I did a bunch of testing on a new repo and got a different error, but still couldn't get it to pass successfully. Unfortunately, I can't figure it out and hopefully someone else will come around and be able to help. I'll be closing this PR and best of luck!

2021-10-05 23:06 UTC, closed without merging

2021-10-05 23:10 UTC, Victoria-DR commented
Huh, looks like it works now. Not sure why though. 🤔

2021-10-06 06:11 UTC, priyansh32 commented
Thanks for the efforts @Victoria-DR. 
I have added another app for this, It [trafico bot](https://github.com/marketplace/trafico-pull-request-labeler) that labelled the PR